Sensor2
KatyaEvdokimova/sensor pull request #1
Opened 2024-09-25 12:21 UTC by KatyaEvdokimova

2024-09-25 12:27 UTC, Ekaterina132479 commented on sensor.py
> -    def run(self):
Цикл бесконечный, это может привести к блокировке программы. Лучше задать количество минут вручную.

2024-09-25 12:29 UTC, Ekaterina132479 commented on sensor.py
> -    def save_to_file(self, value):
Добавить обработку ошибок при работе с файлами.

2024-09-25 12:29 UTC, Ekaterina132479 commented on sensor.py
> +    def save_to_file(self, value):
Добавить обработку ошибок при работе с файлами.

2024-09-25 12:30 UTC, Ekaterina132479 commented on sensor.py
> +    def run(self):
Цикл бесконечный, это может привести к блокировке программы. Лучше задать количество минут вручную.

2024-10-01 15:30 UTC, arybin93 requested changes
Учесть комментарии, разрешить Merge Conflict перед merge в master

2024-10-01 15:30 UTC, arybin93 commented on sensor.py
> +    interval = (20, 30)  # Интервал значений (например, температура от 20 до 30 градусов)
Добавьте, плиз, скрин запуска и работы программы

2024-10-01 15:30 UTC, arybin93 commented on sensor.py
> +    interval = (20, 30)  # Интервал значений (например, температура от 20 до 30 градусов)
Доработайте так, чтобы можно было вводить вводные параметры из консоли при запуске

2024-10-01 15:30 UTC, arybin93 commented on sensor.py
> +    interval = (20, 30)  # Интервал значений (например, температура от 20 до 30 градусов)
![image](https://github.com/user-attachments/assets/0e804115-bc43-4214-ac9d-99a118bbb5af)

2024-10-26 12:04 UTC, merged